# Uncomment the next line to define a global platform for your project
platform :ios, '11.4'

target 'DI' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Swinject'

  # Pods for DI

  target 'DITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DIUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
